apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluxcd-demo
  namespace: flux-system
spec:
  releaseName: emrchiver-ms
  targetNamespace: flux-system
  chart:
    git: git@github.com:azeemkhan0917/flux-system.git
    path: helm-charts/emrchiver-ms
    ref: main