apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "emrchiver-ms.serviceAccountName" . }}
  labels: {{- include "emrchiver-common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "emrchiver-common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.serviceAccount.annotations }}
    {{- include "emrchiver-common.tplvalues.render" (dict "value" .Values.serviceAccount.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "emrchiver-common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
