# Default values for emrchiver-ms.
configmap:
   json_data: |-
    {
      "fruit":"Apple",
      "size":"Large",
      "color":"Red"
    }

replicaCount: 1

deploymentAnnotations: {}

updateStrategy: "RollingUpdate"

image:
  repository: 
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
capabilities:
  add: ["NET_ADMIN", "SYS_TIME"]
runAsUser: 1000
allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: 
      paths:
        - path: /
          pathType: 
  tls: []

resources: {}


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  

nodeSelector: {}

tolerations: []

affinity: {}

networkPolicy:
  create: true

liveness:
  path: "/"

readiness:
  path: "/"