apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluxcd-demo
  namespace: test-helm
spec:
  releaseName: emrchiver-ms
  targetNamespace: test-helm
  chart:
    git: git@github.com:azeemkhan0917/flux-system.git
    path: helm-charts/emrchiver-ms
    ref: main