apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  config.json: |-
    {
{{- range $key, $val := .Values.configmap.json_data }}
{{ $key | quote | indent 6}}: {{ $val | quote }}
{{- end}}
    }