{{- if .Values.networkPolicy.create -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "emrchiver-ms.fullname" . }}
  labels:
    {{- include "emrchiver-ms.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "emrchiver-ms.labels" . | nindent 4 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
{{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
{{- end }}
  egress:
{{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}

