apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "emrchiver-ms.serviceAccountName" . }}
  labels:
    {{- include "emrchiver-ms.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
